name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Com.Ve.TcpServer.sln
    - name: Build
      run: dotnet build Com.Ve.TcpServer.sln --no-restore
    - name: Test
      run: dotnet test Com.Ve.TcpServer.sln --no-build --verbosity normal
    - name: package
      run: dotnet pack Com.Ve.TcpServer.sln --configuration Release
    - name: nuget
      run: dotnet nuget push "bin/Release/Com.Ve.TcpServer.1.0.0.nupkg"  --api-key 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 --source "https://github.com/karthick5206/Com.Ve.TcpServer" 
