name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Com.Ve.TcpServer.sln
    - name: Build
      run: dotnet build Com.Ve.TcpServer.sln --no-restore
    - name: Test
      run: dotnet test Com.Ve.TcpServer.sln --no-build --verbosity normal
    - name: package
      run: dotnet pack Com.Ve.TcpServer.sln -c Release -o out
    - name: nuget      
      run: dotnet nuget push ./out/*.nupkg --api-key "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" --source "https://nuget.pkg.github.com/karthick5206/index.json" --skip-duplicate
    
